#!/usr/bin/env python
import sys
import time
import subprocess

import pyautogui
from PIL import Image
import numpy

subprocess.run(["xfce4-popup-whiskermenu"])
time.sleep(.2)
pyautogui.typewrite("dumb")
time.sleep(0.2)
if sys.argv[1] in ["a", "b"]:
    if sys.argv[1] == "b":
        pyautogui.click(200, 630, button="secondary")
    a = pyautogui.screenshot(region=(0, 530, 467, 1080 - 530))
    a = Image.fromarray(numpy.concatenate((numpy.array(a)[:300], numpy.array(a)[-80:])))
else:
    a = pyautogui.screenshot(region=(8, 609, 300, 43))

a.save(sys.argv[2] + ".jpg")
pyautogui.press("esc")
pyautogui.press("esc")
