#!/usr/bin/env python

import re
from urllib.request import urlopen
import json
from pathlib import Path

with urlopen("https://raw.githubusercontent.com/pypa/trove-classifiers/main/src/trove_classifiers/__init__.py") as response:
    content = response.read().decode()

classifiers = re.findall("['\"](License :: [^'\"]+)['\"]", content)
current = json.loads(Path(__file__, "../polycotylus/trove-spdx-licenses.json").resolve().read_bytes())

for classifier in classifiers:
    if classifier not in current:
        print(classifier)
