#!/usr/bin/env sh
curl -L https://raw.githubusercontent.com/spdx/license-list-data/main/json/licenses.json | jq --raw-output '.licenses[] | select(.isOsiApproved) | .licenseId' > polycotylus/spdx-osi-approved.txt
curl -L https://raw.githubusercontent.com/spdx/license-list-data/main/json/exceptions.json | jq --raw-output '.exceptions[].licenseExceptionId' > polycotylus/spdx-exceptions.txt
